<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sdk\Flow.SDK\Flow.SDK.csproj" />
    <ProjectReference Include="..\..\src\Flow.Automation\Flow.Automation.csproj" />
    <ProjectReference Include="..\..\src\Flow.Core\Flow.Core.csproj" />
    <ProjectReference Include="..\..\src\Flow.Shared\Flow.Shared.csproj" />
  </ItemGroup>

</Project>
