#define AUTO_GENERATED_FLAG

namespace Flow.SDK.Generators;

internal static class Constants
{
    internal const string NewLine =
#if UNIX || IOS
        "\r\n";
#elif WIN32
        "\n";
#else
        "\n";
#endif


    internal const string GeneratorError =
        """
        /*
            Generating failed.
            Error or trace: 
        $error
            Modify or check your source might help.
        */
        """;

    #region Static Node Source

    internal const string StaticNodeAttributeString
        = "Flow.SDK.Attributes.StaticNodeAttribute";

    internal const string StaticNodeSourceHeader =
#if AUTO_GENERATED_FLAG
        """
        // <auto-generated/ >
        // Generated by Flow.SDK.Generators.Generator.
        // Used to convert a static method to a node object.
        //
        // Ensure you have added references to the following projects: 
        // - Flow.SDK
        // - Flow.SDK.Generators
        // - Flow.Shared

        using Flow.Shared.Abstractions;
        using Flow.Shared.Enums;
        using Flow.Shared.Metadata;
        using Flow.Shared.Results;
        using Flow.Shared.Models;
        using Flow.SDK;
        using Flow.SDK.Attributes;
        using Flow.Shared;

        #nullable enable
        """;
#else
    """
        // Generated by Flow.SDK.Generators.Generator.
        // Used to convert a static method to a node object.
        //
        // Ensure you have added references to the following projects: 
        // - Flow.SDK
        // - Flow.SDK.Generators
        // - Flow.Shared

        using Flow.Shared.Abstractions;
        using Flow.Shared.Enums;
        using Flow.Shared.Metadata;
        using Flow.Shared.Results;
        using Flow.Shared.Models;
        using Flow.SDK;
        using Flow.SDK.Attributes;
        using Flow.Shared;

        #nullable enable
        """;
#endif

    internal const string InputMetadataTemplate =
        """
        new ParameterMetadata()
        {
            Index = $paramIndex, 
            Identifier = "$paramName", 
            Description = "$paramDescription", 
            Type = typeof($paramType), 
            IsRequired = true, 
            DefaultValue = $paramDefaultValue,
        },
        """;

    internal const string OutputMetadataTemplate =
        """
        new ParameterMetadata
        {
            Index = 0, 
            Identifier = "Result", 
            Description = "Result of $paramName operation.", 
            Type = typeof($paramType), 
            IsRequired = true, 
            DefaultValue = $paramDefaultValue,
        },
        """;

    internal const string StaticNodeExecuteParamTemplate =
        "($paramType)Inputs![($index)]!";

    internal const string StaticNodeExecuteCallVoidOriginTemplate =
        "$originMethodName($paramString)";

    internal const string StaticNodeExecuteCallNonVoidOriginTemplate =
        """
        var result = $originMethodName($paramString);
        Outputs[0] = result;
        """;

    internal const string StaticNodeExecuteSuccessfullyResult =
        "Result = VoidResult.Ok();";

    internal const string StaticNodeCtorTemplate =
        """
        public $className() : base(NodeMetadata, InputMetadata, OutputMetadata)
        {
            Inputs = new object?[$inputLength];
            Outputs = new object?[$outputLength];
        }
        """;

    internal const string StaticNodeSourceTemplate =
        """
        // Generated at $generatedTimestamp
        $sourceHeader

        namespace $namespace
        {
            public partial class $collectionName
            {
                public class $nodeClassName : Node, IExecutable
                {
                    internal static NodeMetadata NodeMetadata = new()
                    {
                        Id = new Guid("$nodeGuid"),
                        Identifier = "$nodeName",
                        Description = "$nodeDescription"
                    };
                    
                    internal static ParameterMetadata[]? InputMetadata =
                    [
        $inputMetadata
                    ];
                    
                    internal static ParameterMetadata[]? OutputMetadata =
                    [
        $outputMetadata
                    ];
                    
        $ctor
                    
                    /// <inheritdoc />
                    public void Execute()
                    {
                        try
                        {
        $executeMethodBody
                        }
                        catch (Exception ex)
                        {
                            Result = VoidResult.Err(ex);
                        }
                    }
                }
            }
        }
        """;
    
    #endregion

    #region Static Saync Node Source

    internal const string StaticAsyncNodeAttributeString
        = "Flow.SDK.Attributes.StaticAsyncNodeAttribute";

    internal const string StaticAsyncNodeExecuteParamTemplate =
        "($paramType)Inputs![($index)]!";

    internal const string StaticAsyncNodeExecuteCallVoidOriginTemplate =
        "$originMethodName($paramString)";

    internal const string StaticAsyncNodeSourceHeader =
#if AUTO_GENERATED_FLAG
        """
        // <auto-generated/ >
        // Generated by Flow.SDK.Generators.Generator.
        // Used to convert a static method to a node object.
        //
        // Ensure you have added references to the following projects: 
        // - Flow.SDK
        // - Flow.SDK.Generators
        // - Flow.Shared

        using Flow.Shared.Abstractions;
        using Flow.Shared.Enums;
        using Flow.Shared.Metadata;
        using Flow.Shared.Results;
        using Flow.Shared.Models;
        using Flow.SDK;
        using Flow.SDK.Attributes;
        using Flow.Shared;

        #nullable enable
        """;
#else
    """
        // Generated by Flow.SDK.Generators.Generator.
        // Used to convert a static method to a node object.
        //
        // Ensure you have added references to the following projects: 
        // - Flow.SDK
        // - Flow.SDK.Generators
        // - Flow.Shared

        using Flow.Shared.Abstractions;
        using Flow.Shared.Enums;
        using Flow.Shared.Metadata;
        using Flow.Shared.Results;
        using Flow.Shared.Models;
        using Flow.SDK;
        using Flow.SDK.Attributes;
        using Flow.Shared;

        #nullable enable
        """;
#endif
    
    internal const string StaticAsyncNodeSourceTemplate =
        """
        // Generated at $generatedTimestamp
        $sourceHeader

        namespace $namespace
        {
            public partial class $collectionName
            {
                public class $nodeClassName : Node, IAsyncExecutable
                {
                    internal static NodeMetadata NodeMetadata = new()
                    {
                        Id = new Guid("$nodeGuid"),
                        Identifier = "$nodeName",
                        Description = "$nodeDescription"
                    };
                    
                    internal static ParameterMetadata[]? InputMetadata =
                    [
        $inputMetadata
                    ];
                    
                    internal static ParameterMetadata[]? OutputMetadata =
                    [
        $outputMetadata
                    ];
                    
        $ctor
                    
                    /// <inheritdoc />
                    public async Task ExecuteAsync()
                    {
                        try
                        {
        $executeMethodBody
                        }
                        catch (Exception ex)
                        {
                            Result = VoidResult.Err(ex);
                        }
                    }
                }
            }
        }
        """;

    #endregion

    #region Dependency Source

    internal const string DependencyAttributeString
        = "Flow.SDK.Attributes.DependencyAttribute";

    internal const string I18NRequiredAttributeString
        = "Flow.SDK.Attributes.I18NRequiredAttribute";

    internal const string DependencySourceHeader =
#if AUTO_GENERATED_FLAG
        """
        // <auto-generated/ >
        // Generated by Flow.SDK.Generators.Generator.
        // Used to generate the partial class includes util methods of a dependency.
        //
        // Ensure you have added references to the following projects: 
        // - Flow.SDK
        // - Flow.SDK.Generators
        // - Flow.Shared

        using Flow.Shared.Abstractions;
        using Flow.Shared.Enums;
        using Flow.Shared.Metadata;
        using Flow.Shared.Results;
        using Flow.Shared.Models;
        using Flow.Shared;
        using Flow.SDK;
        using Flow.SDK.Utils;
        using Flow.SDK.Attributes;
        using Flow.SDK.Abstractions;

        #nullable enable
        """;
#else
    """
        // Generated by Flow.SDK.Generators.Generator.
        // Used to generate the partial class includes util methods of a dependency.
        //
        // Ensure you have added references to the following projects: 
        // - Flow.SDK
        // - Flow.SDK.Generators
        // - Flow.Shared

        using Flow.Shared.Abstractions;
        using Flow.Shared.Enums;
        using Flow.Shared.Metadata;
        using Flow.Shared.Results;
        using Flow.Shared.Models;
        using Flow.Shared;
        using Flow.SDK;
        using Flow.SDK.Utils;
        using Flow.SDK.Attributes;
        using Flow.SDK.Abstractions;

        #nullable enable
        """;
#endif

    internal const string DependencyBase
        = "Dependency";

    internal const string DependencyI18NRequiredBase
        = "Dependency, II18NRequired";

    internal const string DependencyI18NField
        = "private I18NHelper I18nHelper;";

    internal const string NodeTypesDictItemTemplate
        = "{ $nodeMetadata, $nodeType },";

    internal const string I18NInitializeMethodHeader =
        """
        private static void I18NInitialize()
        {
        $i18nInitMethodBody
        }
        """;

    internal const string I18NInitializeMethodBodySourceTemplate =
        """
        I18NHelper.TranslateAndModifyRecognizableObject(ref $i18nInitRequiredObj.NodeMetadata);
        I18NHelper.TranslateAndModifyRecognizableObjects(ref $i18nInitRequiredObj.InputMetadata);
        I18NHelper.TranslateAndModifyRecognizableObjects(ref $i18nInitRequiredObj.OutputMetadata);
        """;

    internal const string DependencyClassSourceTemplate =
        """
        // Generated at $generatedTimestamp
        $sourceHeader

        $nodeUsings
            
        namespace $namespace
        {
            public partial class $dependencyClassName : $dependencyBase
            {
        $i18nHelper   
                
                private static List<string> _nodeClasses = new()
                {
        $nodeClasses
                };
                
                public override Dictionary<NodeMetadata, Type> NodeTypes { get; } = new()
                {
        $nodeTypes
                };
                
        $i18nInitMethod
            }
        }
        """;
    
    #endregion
}