<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sdk\Flow.SDK.Dependency\Flow.SDK.Dependency.csproj" />
    <ProjectReference Include="..\..\src\Flow.Shared\Flow.Shared.csproj" />
    <ProjectReference Include="..\..\sdk\Flow.SDK.Dependency.Generators\Flow.SDK.Dependency.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
