namespace Flow.SDK.Plugins.Generators;

internal static class Constants
{
    internal const string SourceHeader =
"""
// <auto-generated/ >
// Generated by Flow.SDK.Generators.Generator.
// Used to convert a static method to a node object.
//
// Ensure you have added references to the following projects:
// - Flow.SDK
// - Flow.SDK.Generators
// - Flow.Shared

using Flow.Shared.Abstractions;
using Flow.Shared.Enums;
using Flow.Shared.Metadata;
using Flow.Shared.Results;
using Flow.SDK.Plugins;
using Flow.SDK.Plugins.Attributes;
using Flow.Shared;

#nullable enable
""";

    internal const string StaticNodeAttributeDisplayString 
        = "Flow.SDK.Plugins.Attributes.StaticNodeAttribute";

    internal const string InputMetadataTemplate =
"""
new ParameterMetadata(
    Index: $$PARAM_INDEX$$, 
    Name: "$$PARAM_NAME$$", 
    Description: "$$PARAM_DESCRIPTION$$", 
    Type: typeof($$PARAM_TYPE$$), 
    IsRequired: true, 
    DefaultValue: $$PARAM_DEFAULT_VALUE$$),
""";
    
    internal const string OutputMetadataTemplate =
"""
new ParameterMetadata(
    Index: 0, 
    Name: "Result", 
    Description: "Result of $$PARAM_NAME$$ operation.", 
    Type: typeof($$PARAM_TYPE$$), 
    IsRequired: true, 
    DefaultValue: $$PARAM_DEFAULT_VALUE$$),
""";
    
    internal const string StaticNodeSourceTemplate = 
"""
// Generated at $$GENERATED_TIMESTAMP$$
$$SOURCE_HEADER$$

namespace $$NAMESPACE$$
{
    public partial class $$COLLECTION_NAME$$
    {
        public class $$NODE_CLASS_NAME$$ : INode, IExecutable
        {
            private static readonly NodeMetadata NodeMetadata = new()
            {
                Id = new Guid("$$NODE_GUID$$"),
                Name = "$$NODE_NAME$$",
                Description = "$$NODE_DESCRIPTION$$"
            };
            
            /// <inheritdoc />
            public NodeMetadata Metadata => NodeMetadata;
            
            /// <inheritdoc />
            public Guid RuntimeId { get; init; }
            
            /// <inheritdoc />
            public NodeStatus Status { get; set; }
            
            private static readonly ParameterMetadata[]? InputMetadata =
            [
$$INPUT_METADATA$$
            ];
            
            /// <inheritdoc />
            public ParameterMetadata[]? InputVariableMetadata => InputMetadata;
            
            /// <inheritdoc />
            public object?[]? Inputs { get; init; }
            
            private static readonly ParameterMetadata[]? OutputMetadata =
            [
$$OUTPUT_METADATA$$
            ];
            
            /// <inheritdoc />
            public ParameterMetadata[]? OutputVariableMetadata => OutputMetadata;
            
            /// <inheritdoc />
            public object?[]? Outputs { get; init; }
            
            /// <inheritdoc />
            public Result? Result { get; private set; }
            
$$CTOR$$
            
            /// <inheritdoc />
            public void Execute()
            {
                try
                {
                    $$EXECUTE_METHOD_BODY$$
                }
                catch (Exception ex)
                {
                    Result = new Result(
                        IsCompleted: false, 
                        IsSuccess: false, 
                        Exception: ex, 
                        Message: "Failed to execute $$METHOD_NAME$$ operation.");
                }
            }
        }
    }
}
""";
}