namespace Flow.SDK.Plugins.Generators;

public static class Constants
{
    public const string Header =
"""
// <auto-generated/ >
// Generated by Flow.SDK.Generators.Generator.
// Used to convert a static method to a node object.
//
// Ensure you have added references to the following projects:
// - Flow.SDK
// - Flow.SDK.Generators
// - Flow.Shared

using Flow.Shared.Abstractions;
using Flow.Shared.Enums;
using Flow.Shared.Metadata;
using Flow.Shared.Results;
using Flow.SDK.Plugins;
using Flow.SDK.Plugins.Attributes;
using Flow.Shared;

#nullable enable
""";
}