using System;
using Microsoft.CodeAnalysis;

namespace Flow.SDK.Plugins.Generators;

#pragma warning disable RS1038
[Generator]
#pragma warning restore RS1038
public class InternalNodeGenerator : IIncrementalGenerator
{
    private const string Header =
"""
// <auto-generated/ >
// Generated by Flow.SDK.Generators.Generator.
// Used to convert a static method to a node object.
using Flow.SDK.Plugins;
using Flow.SDK.Plugins.Node.Attributes;
""";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        throw new NotImplementedException();
    }
}