using System;
using Microsoft.CodeAnalysis;

namespace Flow.SDK.Plugins.Generators;

#pragma warning disable RS1038
[Generator(LanguageNames.CSharp)]
#pragma warning restore RS1038
public class InternalNodeGenerator : IIncrementalGenerator
{
    private const string Header =
"""
// <auto-generated/ >
// Generated by Flow.SDK.Generators.Generator.
// Used to convert a static method to a node object.
//
// Ensure you have added references to the following projects:
// - Flow.SDK
// - Flow.SDK.Generators
// - Flow.Shared

using Flow.SDK.Plugins;
using Flow.SDK.Plugins.Node.Attributes;
using Flow.Shared;

#nullable enable
""";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        throw new NotImplementedException();
    }
}